<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Post>
 */
class PostFactory extends Factory
{
    private static int $dateIncrement = 0;
    protected static int $titleIndex = 0;
    protected static int $teaserIndex = 0;
    protected static array $titles = [
        "Rise and Shine!",
        "Believe in You",
        "Dreams into Plans",
        "Grasp the Day",
        "Beyond the Fear",
        "Seize Success",
        "Aim High, Win Big",
        "Dare to Dream",
        "Build Your Path",
        "Empower Your Mind",
        "Ignite Your Spark",
        "Chase the Light",
        "Grow and Glow",
        "Unleash Power",
        "Live Passionately",
        "Lead with Love",
        "Stay on Course",
        "Vision to Victory",
        "Craft Your Life",
        "Forge Ahead",
        "Elevate Every Day",
        "Pursue Progress",
        "Brave the Odds",
        "Soar to Peaks",
        "Break Barriers",
        "Strength in You",
        "Redefine Limits",
        "Beat the Blues",
        "Own Your Story",
        "Thrive, Not Just Survive",
        "Transform Trials",
        "Bounce Back",
        "Joy in Journey",
        "Navigate to Win",
        "Sparkle and Shine",
        "Harbor Hope",
        "Fuel Your Fire",
        "Rally and Rise",
        "Master the Moment",
        "Conquer Today",
        "Brighter Beyond",
        "Celebrate Self",
        "Boundless Bliss",
        "Achieve and Ascend",
        "Majesty of Now",
        "Journey Joyfully",
        "Grit to Great",
        "Embrace Endeavor",
        "Peak Performance",
        "Blaze Your Trail",
        "Inspire Impact",
        "Cultivate Courage",
        "Navigate Dreams",
        "Vibrant Vision",
        "Unfold Potential",
        "Cherish Challenges",
        "Leap and Land",
        "Summit of Success",
        "Renew and Rejoice",
        "Quest for Quests",
        "Sprint to Splendor",
        "Craft and Create",
        "Flourish in Fight",
        "Balance and Bloom",
        "Awaken Awe",
        "Dive into Day",
        "Miracle of Mind",
        "Harvest Happiness",
        "Sustain Spirit",
        "Connect and Conquer",
        "Lift and Lead",
        "Glow with Goals",
        "Hope and Heal",
        "Momentum of Motive",
        "Trail of Triumph",
        "Nourish the Novel",
        "Persist and Prevail",
        "Revive and Thrive",
        "Stellar Strides",
        "Unveil Vitality",
        "Wave of Wonder",
        "Zest for Zenith",
        "Anchor in Aspire",
        "Breathe Belief",
        "Climb, Claim, Cheer",
        "Dazzle with Deeds",
        "Envision and Enact",
        "Fan Your Flames",
        "Gather Grit",
        "Honor Your Hue",
        "Ink Your Ideals",
        "Jubilate Journey",
        "Kindle Kinship",
        "Link to Leap",
        "Mold Your Moments",
        "Nurture Novelty",
        "Orchestrate Opportunity",
        "Paint Your Passion",
        "Quest for Quality",
        "Rally for Radiance",
    ];
    protected static array $teasers = [

        "Every morning brings with it a hidden gift; unwrap it with enthusiasm and see where it takes you.",
        "Fear not the unknown, for it's the soil where the seeds of growth and innovation are planted and nurtured.",
        "Transform your every day into a masterpiece of your own design, painted with the colors of hard work and determination.",
        "Wear your courage like an armor, unyielding and shining, turning every challenge into a battle won before it's fought.",
        "Persistence carves paths through mountains, turns deserts into oases, and transforms the ordinary into the extraordinary.",
        "If you don't dare to build your own dreams, you might find yourself hired to build someone else's, wondering where your own went.",
        "Each small step, taken with conviction, is a giant leap in the tapestry of your life's grand design.",
        "Cherish not just the destination but also the journey, for it is in the journey that life unfolds its true treasures and lessons.",
        "In every challenge, look for the opportunity hidden beneath, wrapped in the disguise of difficulty but shining with potential.",
        "Believing in yourself is the cornerstone of greatness; it's the silent force that propels you forward when the path seems insurmountable.",
        "Let your dreams be bigger than your fears and your actions louder than your words.",
        "Awaken to the possibility that today could be the best day of your life.",
        "Embrace the power within you to create, achieve, and transform anything you desire.",
        "The journey to greatness begins with a single step filled with purpose and passion.",
        "Your potential is endless; tap into it and let your talents soar to new heights.",
        "Face each day with courage and conviction, knowing you have the strength to overcome anything.",
        "Transform obstacles into opportunities and challenges into victories through perseverance.",
        "Illuminate the world with your brilliance by daring to dream and daring to do.",
        "Harness the power of positivity to fuel your journey towards achieving your dreams.",
        "Let each day be a canvas for your creativity, painting your life with bold colors and bright moments.",
        "Believe in the magic of new beginnings and the power of fresh starts.",
        "Dedicate yourself to personal growth and watch as new doors open for you.",
        "Cultivate gratitude, and let it be the foundation of your strength and success.",
        "Your journey is uniquely yours, embrace it with passion and relentless drive.",
        "Find strength in adversity, and let every challenge sculpt your masterpiece.",
        "Every day holds the promise of a miracle; keep your heart open to the possibilities.",
        "Be the architect of your future, building bridges to your dreams with determination.",
        "Let your spirit soar to new heights, powered by ambition and guided by integrity.",
        "Discover the power of your voice and let it echo with messages of hope and resilience.",
        "Chart your own course, fueled by curiosity and illuminated by your inner light.",
        "Nurture your dreams with dedication and watch them blossom into realities.",
        "Forge ahead with courage, letting your fears dissolve into the shadows of the past.",
        "Embrace change as the canvas for your next masterpiece, painted with bold strokes.",
        "Let your resilience be the key that unlocks doors to uncharted territories.",
        "Cultivate a mindset of abundance and witness the transformation in your life journey.",
        "Anchor your actions in kindness, and navigate through life's storms with grace.",
        "Harness the power of reflection to propel you forward into a future of possibilities.",
        "Elevate your aspirations, reaching for the stars with unwavering faith and determination.",
        "Illuminate your path with the light of perseverance and the glow of self-belief.",
        "Embark on a quest for knowledge, letting each discovery fuel your boundless curiosity.",
        "Transform obstacles into stepping stones towards your grandest visions.",
        "Let passion be the wind beneath your wings, soaring to new heights of achievement.",
        "Cultivate inner peace as the foundation for external success and harmony.",
        "Embrace your unique journey, celebrating each step towards self-realization.",
        "Foster a spirit of gratitude, and watch as doors of opportunity swing wide open.",
        "Dare to dream big, and then take the leap into making those dreams your reality.",
        "Enrich your life with new experiences, savoring the growth that comes with each.",
        "Cherish your moments of triumph, and let them inspire you through challenges.",
        "Invest in your personal growth, for it is the most rewarding investment you can make.",
        "Lead with empathy and integrity, becoming a beacon of inspiration for those around you.",
        "Nurture resilience; let it be your shield against the storms of life.",
        "Embrace change as a catalyst for growth, not a barrier to success.",
        "Cultivate a mindset of abundance, seeing opportunity in every challenge.",
        "Let kindness be your guide, and you'll find strength in compassion.",
        "Seek wisdom in silence, for it speaks volumes in the journey of self-discovery.",
        "Your actions today are the seeds for the garden of your future.",
        "Find beauty in simplicity, letting it remind you of life's true treasures.",
        "Hold onto hope, for it lights the path in the darkest of times.",
        "Trust in the journey, even when the destination is not in sight.",
        "Be the architect of your fate, building a life of purpose and passion.",
        "Open your heart to the symphony of possibilities that dance in the realm of uncertainty.",
        "With each step forward, let the echoes of your courage reverberate through the corridors of time.",
        "In the crucible of challenge, forge the steel of resilience, shaping a destiny that knows no bounds.",
        "Sow the seeds of determination in the fertile soil of your aspirations, harvesting a bounty of triumphs.",
        "Embrace the mosaic of life's experiences, weaving threads of resilience into the tapestry of your journey.",
        "Illuminate the path ahead with the torch of perseverance, guiding you through the labyrinth of adversity.",
        "With unwavering resolve, scale the peaks of possibility, where dreams unfurl their wings and take flight.",
        "Cradle the embers of hope in the palm of your hand, for they possess the power to ignite the flames of transformation.",
        "Dive deep into the ocean of self-discovery, where the pearls of wisdom await in the depths of introspection.",
        "Let the echoes of your dreams reverberate through the corridors of possibility, painting the canvas of your destiny with strokes of resilience and determination.",
        "Embrace the melody of possibility that resonates in the silence between heartbeats.",
        "With every challenge comes an opportunity to sculpt your destiny with unwavering resolve.",
        "Sow the seeds of resilience in the garden of your soul, nurturing them into mighty oaks of strength.",
        "In the alchemy of life, transform adversity into the raw material for your greatest achievements.",
        "Unleash the boundless potential within you, casting aside the shackles of doubt and fear.",
        "Navigate the labyrinth of uncertainty with a compass forged from the steel of determination.",
        "Embrace the rhythm of change, for it is the heartbeat of growth and evolution.",
        "In the cathedral of your dreams, let the echoes of possibility resound with unwavering clarity.",
        "Forge your path with the hammer of perseverance, shaping a destiny that knows no limits.",
        "Let the symphony of your spirit serenade the world with the melody of resilience and courage.",
        "In the garden of life, tend to the seeds of ambition, nurturing them into towering pillars of success.",
        "Amidst the chaos of uncertainty, find solace in the certainty of your own strength and resilience.",
        "With every sunrise, awaken to the boundless possibilities that await on the horizon of your journey.",
        "Embrace the whispers of intuition, guiding you along the winding paths of destiny.",
        "The symphony of success is composed of countless notes of perseverance and determination.",
        "Navigate the labyrinth of challenges with the compass of courage, knowing each obstacle is a stepping stone to greatness.",
        "In the mosaic of life, let every setback be a colorful tile in the masterpiece of your resilience.",
        "Embrace the journey, for it is the winding road that leads to the summit of your aspirations.",
        "With unwavering faith in yourself, turn stumbling blocks into stepping stones towards your dreams.",
        "Let the echoes of your ambition reverberate through the corridors of time, leaving an indelible mark on the tapestry of history.",
        "Amidst the chaos, find serenity in the quiet strength that resides within.",
        "Forge ahead with unwavering determination, knowing that every step brings you closer to your dreams.",
        "In the tapestry of life, weave threads of resilience and courage into every stitch.",
        "Embrace the journey with open arms, for it is the path that molds you into who you are meant to be.",
        "With every challenge, discover the hidden opportunities waiting to be unearthed.",
        "Let the flames of passion ignite your soul, guiding you through the darkest of nights.",
        "In the dance of life, move with purpose and intention, leaving a trail of inspiration in your wake.",
        "With each sunrise, embrace the promise of a new beginning and the potential it holds.",
        "Chart your own course, guided by the compass of your dreams and the stars of your aspirations.",
        "Believe in the power of your own resilience, for it is the key that unlocks endless possibilities.",
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $title = self::$titles[self::$titleIndex];
        $teaser = self::$teasers[self::$teaserIndex];

        self::$titleIndex++;
        self::$teaserIndex++;

        return [
            'title' => $title,
            'teaser' => $teaser,
            'created_at' => now()->subDays(100)->addDays(self::$dateIncrement++),
        ];
    }
}
